export const userMessage = {
  IMAGE_URL_LENGTH: 'Image url length must be from 1 to 400',
  IMAGE_URL_MUST_BE_STRING: 'Image url must be a string',
  USERNAME_LENGTH: 'Username length must be from 1 to 50',
  USERNAME_MUST_BE_STRING: 'Username must be a string',
  WEBSITE_LENGTH: 'Website length must be from 1 to 200',
  WEBSITE_MUST_BE_STRING: 'Website must be a string',
  LOCATION_LENGTH: 'Location length must be from 1 to 200',
  LOCATION_MUST_BE_STRING: 'Location must be a string',
  BIO_LENGTH: 'Bio length must be from 1 to 200',
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_A_STRING: 'Name must be a string',
  NAME_LENGTH_MUST_BE_FROM_1_TO_100: 'Name length must be from 1 to 100',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_IS_INVALID: 'Email is invalid',
  PASSWORD_IS_REQUIRED: 'Password is required',
  PASSWORD_MUST_BE_A_STRING: 'Password must be a string',
  PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50: 'Password length must be from 6 to 50',
  PASSWORD_MUST_BE_STRONG:
    'Password must be 6-50 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  CONFIRM_PASSWORD_IS_REQUIRED: 'Confirm password is required',
  CONFIRM_PASSWORD_MUST_BE_A_STRING: 'Confirm password must be a string',
  CONFIRM_PASSWORD_LENGTH_MUST_BE_FROM_6_TO_50: 'Confirm password length must be from 6 to 50',
  CONFIRM_PASSWORD_MUST_BE_STRONG:
    'Confirm password must be 6-50 characters long and contain at least 1 lowercase letter, 1 uppercase letter, 1 number, and 1 symbol',
  CONFIRM_PASSWORD_MUST_BE_THE_SAME_AS_PASSWORD: 'Confirm password must be the same as password',
  DATE_OF_BIRTH_MUST_BE_ISO8601: 'Date of birth must be ISO8601',
  NOT_FOUND_ACCOUT: 'Account not found',
  NOT_FOUND_ACCESSTOKEN: 'Access token not found',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  REFRESH_TOKEN_INVALID: 'Refresh token is invalid',
  USED_REFRESH_TOKEN_OR_NOT_EXIST: 'Used refresh token or not exist',
  NOT_FOUND_REFRESH_TOKEN: 'Refresh token not found',
  NOT_FOUND_VERIFY_EMAIL: 'Verify email token not found',
  NOT_FOUND_FORGOT_PASSWORD_TOKEN: 'Forgot password token not found',
  USER_NOT_FOUND: 'User not found',
  FORGOT_PASSWORD_TOKEN_INVALID: 'Forgot password token is invalid',
  NOT_VERIFIED: 'User not verified',
  BIO_MUST_BE_STRING: 'Bio must be a string',
  INVALID_ID: 'Invalid id',
  PASSWORD_INCORRECT: 'Password incorrect',
  NOT_LOGGED_IN: 'Not logged in'
} as const
